### ISSUE TITLE
hex-outputs of private key

### ISSUE THREAD

**Issue by alist** [eris-ltd/eris-keys#20]
[eris-contracts.js](https://github.com/eris-ltd/eris-contracts.js) requires a `a proper private key string`, that is not the format stored in `cat ~/.eris/keys/data/[myKeyAddress]/[myKeyAddress]`'s "PrivateKey" field.

Any of 1. a "priv" command for exporting private key, analogous to "pub", 2. storing the "PrivateKey" as HEX compatible with eris-contracts.js, or 3. Documentation on current format of "PrivateKey"/ how to convert would solve this issue.

**Comment by ebuchman** [comment]
couple caveats on this one

1) eris-contracts will soon use eris-keys so there'll be no need to get the priv key out
2) if you have a priv_validator.json around, there's a hex version of the priv key in there
3) if you don't, you can run `mintkey mint <address>` and it will dump the priv_validator.json to the screen, which has the hex priv key

**Comment by ebuchman** [comment]
sorry, in case it wasn't clear, `mintkey` can be found in the `mint-client` collection. 
```
go get github.com/eris-ltd/mint-client
cd $GOPATH/src/github.com/eris-ltd/mint-client
go install ./mintkey
```

**Comment by alist** [comment]
Okay. `mintkey mint <address>` is all that's needed. 

Thanks!
