### ISSUE TITLE
[Crypto] use of experimental, deprecated go-ethereum entropy function

### ISSUE THREAD

**Issue by Gustav-Simonsson** [eris-ltd/eris-keys#23]
Looks like this function was picked up when forking old go-ethereum code: https://github.com/eris-ltd/eris-keys/blob/master/crypto/randentropy/rand_entropy.go#L32

This function was merely intended as an experiment and to discuss merits of XORing in additional sources onto the OS CSPRNG. It was not intended for production use and has since been removed from the code base since we decided the extra complexity and risks that come with it was not worth potential benefits of additional sources in case the OS source through ```crypto/rand``` is weak.

Would recommend switching to using plain ```crypto/rand``` helpers currently used in go-ethereum (these where covered by Ethereum's security audits) : https://github.com/ethereum/go-ethereum/blob/master/crypto/randentropy/rand_entropy.go

**Comment by ebuchman** [comment]
yup I was following this discussion in go-ethereum. is XORing in this kind of information not a standard practice? were actual risks identified? or was it just "better not add more complexity"? I figured I'd keep it at least as a talking point until I had a better idea why it was removed. Seems like if the host OS generator is compromised (as we've seen it has been a few times), this could be a life saviour.

**Comment by Gustav-Simonsson** [comment]
Actual, concrete risks where not identified. It was more "better not add more complexity". And yes, if the OS source is compromised it could in theory still achieve enough entropy since it's combined with a hard KDF. Was thinking especially of the issue on android.

It was mostly informal discussions though, and most people thought the extra complexity was not worth the potential upside in that case.

I still haven't seen a concrete argument why XORing in additional sources (if weak or even completely manipulated) would weaken the original source from crypto/rand - would be interesting to know of there exists specific attack vectors in that scenario.

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-db #333](https://github.com/eris-ltd/eris-db/issues/333) via [**ZenHub**](https://www.zenhub.com/)
