### ISSUE TITLE
[Crypto] consider making eris-keys key files compatible with ethereum clients

### ISSUE THREAD

**Issue by Gustav-Simonsson** [eris-ltd/eris-keys#24]
To get compatibility between all Ethereum clients we worked out a spec for a common key file: https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition

While GCM is nice and we probably should have gone with it instead of CTR + MAC, for the moment Ethereum clients generate key files with CTR.

However the current go-ethereum code supports multiple key formats for backwards compatibility; both scrypt and PBKDF2 for KDF and both CTR and CBC for encryption mode. This could be extended to support GCM if defined by the ```cipher``` field present in version 3 (latest) of the spec.

Would recommend we strive for compatibility between platforms here. This could be done quite easily if eris-keys rebases on go-ethereum's ```crypto/key_store_passphrase.go``` to pickup version 3 of it's key file format and defines it's GCM mode usage by setting the  ```cipher``` field to something like ```aes-128-gcm``` (we use ```aes-128-ctr``` to denote CTR mode)

**Comment by ebuchman** [comment]
yes I would love to do this. thanks for the details.

**Comment by benjaminbollen** [comment]
@zramsay @VoR0220 @AFDudley can we post progress on this issue here ?

**Comment by VoR0220** [comment]
yesh

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-db #334](https://github.com/eris-ltd/eris-db/issues/334) via [**ZenHub**](https://www.zenhub.com/)
