### ISSUE TITLE
first step of README fails

### ISSUE THREAD

**Issue by NodeGuy** [eris-ltd/eris-keys#32]
```
$ eris-keys gen --no-pass
Incorrect Usage.

NAME:
   gen - generate a key

USAGE:
   command gen [command options] [arguments...]

OPTIONS:
   --type "ed25519"			specify the type of key to create. Supports 'secp256k1' and 'ed25519'
   --dir "/Users/david/.eris/keys"	specify the location of the directory containing key files
   --auth 				a password to be used for encrypting keys
```

See http://www.nodeguy.com/make-a-smooth-on-ramp-for-your-project/

**Comment by compleatang** [comment]
that looks quite old. what commit are you on? 

relevant code is on master: 
https://github.com/eris-ltd/eris-keys/blob/master/eris-keys/app.go#L178

**Comment by NodeGuy** [comment]
You're right, it was old.  The bug is in the installation step of the README:

```
go install github.com/eris-ltd/eris-keys
```

That's what I ran, not realizing there was an old copy of eris-keys on my computer.  It appeared to succeed.  The correct command should be:

```
go get github.com/eris-ltd/eris-keys
```
