### ISSUE TITLE
[Keys-Core] use eris-logger

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-keys#52]

**Comment by compleatang** [comment]
this is blocked until we add deamon logging niceties to eris-logger ( https://github.com/eris-ltd/eris-logger/issues/7 ).

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-db #339](https://github.com/eris-ltd/eris-db/issues/339) via [**ZenHub**](https://www.zenhub.com/)
