### ISSUE TITLE
Key gen fails on Docker for Mac 

### ISSUE THREAD

**Issue by tbrooke** [eris-ltd/eris-keys#62]
I am on OSX El Capitan 10.11.6
Eris Platform 0.12.0
Docker for Mac 0.12.0, build 8eab29e

Command:  eris keys gen

Error Message  with debug flag

      eris eris keys gen -d
      Checking Linux Docker socket                  unix:///var/run/docker.sock
      Connecting to Docker                          unix:///var/run/docker.sock
      Loading service definition                    keys
      Defaulting to service                 service=keys
      Service is running                            keys
      Loading service definition                    keys
      Defaulting to service                 service=keys
      Executing container                           keys-a3a80fcb-59ce-4eac-b8e4-cdd046684871
      Manage data containers?              autodata=true
      Data container already exists, am not creating
      Container does not exist. Creating      image=quay.io/eris/keys:0.12.0
      Executing interactive container               interactive-c3de552a-5252-4cde-800e-f72edf51ad54
                                          cmd=[eris-keys gen --no-pass]
                               data container=keys-d5905b81-b24a-43e9-adaa-8be01e983b8e
                                   entrypoint=[]
                                  environment=[ERIS_KEYS_HOST=keys]
                                        image=quay.io/eris/keys:0.12.0
                              ports published=true
                                         user=root
                                         vols=[]
                                      workdir=
        Waiting for container to exit                 interactive-c3de552a-5252-4cde-800e-f72edf51ad54
        Removing container                            interactive-c3de552a-5252-4cde-800e-f72edf51ad54
        Container removed                             interactive-c3de552a-5252-4cde-800e-f72edf51ad54
        Container interactive-c3de552a-5252-4cde-800e-f72edf51ad54 exited with status 1

**Comment by zramsay** [comment]
hi @tbrooke thanks for the bug report. we are aware of some issues with [eris <=> docker] and will report back when things are smoothed out.

**Comment by pietv** [comment]
@tbrooke we have fixed this particular error in the latest release — https://github.com/eris-ltd/eris-cli/releases/tag/v0.12.0-rc2. If you're using the binary version, the `eris version` should return this value `Eris CLI Version: 0.12.0 (a5229ff)` (if you're building it from source, you won't see the git tag in brackets).

I've tried the latest Eris release on both beta (beta21) and stable (build: 10871) and it (`eris keys gen` ) worked for me.

If you're on the latest release still, could you please try the sequence:
```
eris clean -y
eris init
eris services start keys
eris keys gen
```

**Comment by pietv** [comment]
for reference: https://github.com/eris-ltd/eris-cli/issues/780

**Comment by tbrooke** [comment]
Updating to the newest release got it working
Thank You
