### ISSUE TITLE
Keys do not survive a round trip of import and export

### ISSUE THREAD

**Issue by silasdavis** [eris-ltd/eris-keys#90]
For example when previously exported keys are reimported signing with the imported keys does not work (invalid signature error from eris-client):

See here: https://github.com/eris-ltd/eris-contract-bundles/blob/feature/119-document-spec-impl/tests/test.sh#L106

To reproduce `eris chains make` a chain.

`eris keys export --all`

destroy the keys container then

`eris keys import -all`

The keys will no longer work. Need to introduce some unit tests, but logic is spread between cli (dataExport) and eris-keys.

**Comment by pietv** [comment]
@silasdavis thanks! could you specify more clearly what would no longer work?
```
$ eris chains make chain
$ eris keys export --all
$ eris keys import --all
$ eris keys ls
```
The last command works, that is `keys` service is still running, `eris chains make` is still able to create a chain.

**Comment by silasdavis** [comment]
So this bug comes from an issue Jan was having with tests he was running for eris-contract-bundles

```bash
# (over)Kill your containers:
docker rm -f $(docker ps -aq)
# kill any persisted keys
rm -r .eris/keys/* 
# make a chain
eris chains make foo --chain-type simplechain
# export keys for chain
eris key export --all
# Kill containers (really just trying to kill keys and its data container):
docker rm -f $(docker ps -aq)
# start an empty keys (and verify it has no keys):
eris keys ls
# import keys
eris keys import --all
# start a chain
eris chains start foo --init-dir foo
# try to deploy a contract
eris pkgs do --chain foo --address $addr 
# where addr is grepped from addresses.csv in the usual way...
```

However, this worked fine. I also tried with a more complex chain like the one Jan was using and that was also fine. It seems we may have been too quick to blame eris-keys, or it may be we need to add in some other aspect to make keys break.

I'm going to punt this back to @j-h-scheufen. It may be there is some issue in your tests, or we may need some more complex behaviour to produce the bug in eris-db. Either way could you try and create a minimal test case that shows an issues with keys/eris-db.

**Comment by pietv** [comment]
thanks for the answer

**Comment by zramsay** [comment]
this is dealt with in #1133
